on:
  # release ブランチへのプルリクが close されたタイミングで動く
  pull_request:
    # @see https://help.github.com/en/actions/reference/events-that-trigger-workflows#pull-request-event-pull_request
    branches:
      - release
    types: [closed]

name: Create Release

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    
    # マージ以外の理由で close された場合にも動いてしまうので、マージされた場合だけに限定します
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Get release label
        # プルリクに付与された label を取得 / major,minor,patch どのバージョンを上げるかの判定に利用する
        # @see https://github.com/actions-ecosystem/action-release-label
        uses: actions-ecosystem/action-release-label@v1
        id: get-release-label
        
      - name: Get latest tag
        # @see https://github.com/marketplace/actions/actions-ecosystem-action-get-latest-tag
        uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag
    
      - name: Bump Semantic Versioning
        uses: actions-ecosystem/action-bump-semver@v1
        id: bump-semver
        if: ${{ steps.get-release-label.outputs.level != null }}
        with:
          current_version: ${{ steps.get-latest-tag.outputs.tag }}
          level: ${{ steps.get-release-label.outputs.level }}
    

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ steps.bump-semver.outputs.new_version }}
          release_name: ${{ steps.bump-semver.outputs.new_version }}
          draft: false
          prerelease: false
          
