
on:
  release:
    types:
      - released
      - deleted

name: Deploy Test

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Get latest tag-name
        id: get-latest-tag-name
        # @see https://github.com/actions/github-script
        uses: actions/github-script@v1
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            echo "get-latest-tag-name"
            github.release.release()
            
      - name: replace-tag
        id: replace-tag-name
        # v1.x.x を想定している
        # @see https://inokara.hateblo.jp/entry/2016/02/07/110113
        run : |
          echo "event.release.tag_name: ${{ github.event.release.tag_name }}"
          echo "latest.tag_name: ${{ steps.get-latest-tag-name.outputs.release }}"
          # replace [.] -> [-]
          _tag_name=`echo -n ${{ steps.get-latest-tag-name.outputs.release }}`
          echo ::set-output name=replaced_tag_name::${_tag_name//./-}
      - name: print-tag
        env:
          TAG_NAME: ${{ steps.replace-tag-name.outputs.replaced_tag_name}}
        run: |
          echo ${TAG_NAME}
      # @see https://github.com/actions/checkout
      # 最新の tag_name で checkout
      - name: Checkout
        # もし released ならば実行 / deleted のときは不要
        uses: actions/checkout@v2
        if: ${{ github.event.action == 'released' }}
        with:
          # refs/tags/v1.x.x
          ref: "refs/tags/${{ steps.get-latest-tag-name.outputs.release }}"
