
on:
  release:
    types:
      - published
      - deleted
      - unpublished
      - prereleased

name: Deploy Test

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github.event.release) }}
        run: echo "$GITHUB_CONTEXT"
      - name: replace-tag
        id: replace-tag-name
        # v1.x.x を想定している
        # @see https://inokara.hateblo.jp/entry/2016/02/07/110113
        run : |
          echo "release.type: ${{ github.event.release.type }}"
          echo "release.tag_name: ${{ github.event.release.tag_name }}"
          echo "ref: ${{ github.ref }}"
          # replace [.] -> [-]
          _tag_name=`echo -n ${{ github.event.release.tag_name }}`
          echo ::set-output name=replaced_tag_name::${_tag_name//./-}
      - name: print-tag
        env:
          ENV_KEY: ${{ steps.replace-tag-name.outputs.replaced_tag_name}}
        run: |
          echo ${ENV_KEY}
