
on:
  release:
    types:
      - released
      - deleted

name: Deploy Test

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Get latest tag-name
        id: get-latest-tag-name
        # @see https://github.com/marketplace/actions/get-latest-release
        uses: pozetroninc/github-action-get-latest-release@master
        with:
            repository: YukihikoSaito/fastapi-tutorial
      - name: replace-tag
        id: replace-tag-name
        # v1.x.x を想定している
        # @see https://inokara.hateblo.jp/entry/2016/02/07/110113
        run : |
          echo "release.tag_name: ${{ github.event.release.tag_name }}"
          echo "latest.tag_name: ${{ steps.get-latest-tag-name.outputs.release }}"
          # replace [.] -> [-]
          _tag_name=`echo -n ${{ steps.get-latest-tag-name.outputs.release }}`
          echo ::set-output name=replaced_tag_name::${_tag_name//./-}
      - name: print-tag
        env:
          ENV_KEY: ${{ steps.replace-tag-name.outputs.replaced_tag_name}}
        run: |
          echo ${ENV_KEY}
      # @see https://github.com/actions/checkout
      # 最新の tag_name で checkout
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # refs/tags/v1.x.x
          ref: "refs/tags/${{ steps.get-latest-tag-name.outputs.release }}"
