
on:
  release:
    types:
      - published
      - created
      - released
      - deleted

name: Deploy Test

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: echo release type
        run: |
          echo "event.action.type: ${{ github.event.action }}"
          
          
      - name: Get latest tag-name
        id: get-latest-tag-name
        # @see https://github.com/actions/github-script
        # @see https://octokit.github.io/rest.js/v16#repos-get-latest-release
        uses: actions/github-script@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # result を 文字列にする / default は json 形式
          result-encoding: string
          script: |
            const result = await github.repos.getLatestRelease({
              owner: context.repo.owner,
              repo: context.repo.repo
            })
            // console.log(result)
            console.log("Tag name to be deployed: " + result.data.tag_name)
            return result.data.tag_name
            
      - name: replace-tag
        id: replace-tag-name
        # v1.x.x を想定している
        # @see https://inokara.hateblo.jp/entry/2016/02/07/110113
        run : |
          echo "event.release.tag_name: ${{ github.event.release.tag_name }}"
          echo "latest.tag_name: ${{ steps.get-latest-tag-name.outputs.result }}"
          # replace [.] -> [-]
          _tag_name=`echo -n ${{ steps.get-latest-tag-name.outputs.result }}`
          echo ::set-output name=replaced_tag_name::${_tag_name//./-}
      - name: print-tag
        env:
          TAG_NAME: ${{ steps.replace-tag-name.outputs.replaced_tag_name}}
        run: |
          echo ${TAG_NAME}
      # @see https://github.com/actions/checkout
      # 最新の tag_name で checkout
      - name: Checkout
        # deleted のときは不要
        uses: actions/checkout@v2
        if: ${{ github.event.action != 'deleted' }}
        with:
          # refs/tags/v1.x.x
          ref: "refs/tags/${{ steps.get-latest-tag-name.outputs.result }}"
