name: operational test push

# push された時に発火
on: [push]

jobs:
  build:
    # このジョブは GitHubでホストされている ubuntu 上で実行されます
    runs-on: ubuntu-latest

    steps:
      # @see https://github.com/actions/checkout
      # push された最新HEAD を取得
      - name: Checkout
        uses: actions/checkout@v2
      
            
      - name: print-tag
        run: |
          echo TZ=+9 date
          _now=`TZ=+9 date '+%Y.%m.%d%H%M'`
          echo "v${_now}"
          
          
